### ISSUE TITLE
Vultr and Windows

### ISSUE THREAD

**Issue by naasking** [joedicastro/vps-comparison#15]
Cool comparison. On Vultr's supported OS template page [1], they say only Windows 2012 R2 has a $16 charge, but they apparently have a template for Windows 2016 which isn't listed as carrying a charge.

[1] https://www.vultr.com/pricing/

**Comment by joedicastro** [comment]
Thanks! I'll look into that!

**Comment by joedicastro** [comment]
Well, you're right that they offer now (since April 20th) a Windows Server 2016 image, and I will add that, but it has a charge as you can see in the image.

![2017-05-03-211719_1920x1200_scrot](https://cloud.githubusercontent.com/assets/390964/25677476/64628a7c-3046-11e7-9e43-e0229621ad50.png)

The Windows Server 2016 has the same price as the Windows Server 2012 R2 even if I choose the most expensive plan, which by the way I see reasonable since they have to pay for the licenses.

**Comment by naasking** [comment]
Definitely a documentation failure on their pricing page then.

**Comment by joedicastro** [comment]
Yes, and also they didn't put it anything about the charge in the news post.

https://www.vultr.com/news/Deploy-Windows-Server-2016-In-The-Cloud/
